# Generated by Django 5.1.6 on 2025-02-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
